### PR TITLE
Fixed systematic rounding errors

### LINKED ISSUE #88: [Bug] Systematic rounding errors in BC1 decoding
While I discovered and will explain the problem with BC1, this is a general problem that will likely also affect other decoders.

For a while now, I noticed that Pfim-decoded BC1 images tended to have a slightly green tint that was not present in the original DDS. I know that the green tint wasn't present in the original because:

1. The image is pure grayscale (this is dictated by the material model of the game I'm working with), so apart from dithered compression artifacts, I expected no systematic discolorations. This is indeed the case in game, where my graphics card correctly decodes the image as gray.
2. I can look at the image in Paint.Net and there is no green tint. Paint.Net uses DirectX to decode DDS files, so its implementation is most likely correct. It also agrees with the in-game texture.
3. I can convert the DDS to PNG using TexConv and there is no green tint.

After doing the calculations for one block by hand, I can say with certainty that the cause is systematic rounding errors. Pfim does round every operation correctly, but the rounding errors add up and cause the differences I saw.

## Example

This is the simplest example I found. The texture is a 256x256 BC1_UNORM_SRGB-encoded image with a constant color of RGB=47 47 47 (8bit). Every block in the image has the following values:
```
ushort color0 = 0b00110_001100_00110 // RGB565 = 6 12 6
ushort color1 = 0b00101_001011_00101 // RGB565 = 5 11 5
uint bitmap = 0b10101010101010101010101010101010
```

Note: As you can see, all indexes in the bitmap are 2, so I will only explain how `color2` is calculated, since every pixel in the image is identical and uses it.

### DirectX

DirectX uses floating point values to represent colors. First, it converts the RGB565 color to [a floating point vector](https://docs.microsoft.com/en-us/windows/win32/api/directxpackedvector/nf-directxpackedvector-xmloadu565) and [normalizes it](https://github.com/microsoft/DirectXTex/blob/e976dcc6561c82201deb75cd9a94d5634bcc3b41/DirectXTex/BC.cpp#L331). This yields the following colors (here multiplied by 255 to make the comparison with Pfim's 8bit colors easier).

```
color0 = [ 49.354838709677416, 48.57142857142857, 49.354838709677416 ]
color1 = [ 41.12903225806451, 44.52380952380952, 41.12903225806451 ]
```

`color2` is calculated using a simple [floating point linear interpolation](https://github.com/microsoft/DirectXTex/blob/e976dcc6561c82201deb75cd9a94d5634bcc3b41/DirectXTex/BC.cpp#L348):
```
color2 = [ 46.61290322580644, 47.22222222222222, 46.61290322580644 ]
```

Rounding those floating point numbers to get the 8bit RGB, we get the color RGB = 47 47 47.

### Pfim

Pfim uses bitshifts to convert RGB565 to 8bit RGB. The result is as follows:

```
color0 = [ 49, 49, 49 ]
color1 = [ 41, 45, 41 ]
```

`color2` is then calculated as `(2*color0 + 1*color1) / 3` (rounded down, because integer division).
```
color2 = [ 46, 47, 46 ]
```

The final color is RGB = 46 47 46.

### Comparison

As we can see, DirectX's rounded fp numbers for color0 and color1 are the saem as Pfim's. However, due to a lack of precision, Pfim does not calculate color2 correctly. This error seems to manifest as a green tint in many images, because the R and B channels are one too low.

Rounding to the nearest integer for the `/ 3` won't solve the issue. The decimal result of Pfim's `(2*color0+color1)/3` is `[ 46.333, 47.666, 46.333 ]`, so rounding to the nearest int will yield RGB = 46 48 46. While this would somewhat even out the loss in average brightness, it would make the green tint even worse.

### Fix

The easiest solution would be to use floating point numbers, of course. This would trivially solve the rounding errors. The implementation would also be easy to verify for correctness since it has to mirror the DirectX implementation. However, this will likely negatively impact performance as (AFAIK) we do not have (easy) access to the pointer-cast magic and SSE instructions that make DirectX's implementation fast.

One other idea would be to use fixed point numbers (basically just ints with a statically defined maximum). Using a bit of clever arithmetic, we can guarantee that all operations are rounded correctly.

I actually implemented both versions and tested their performance using Pfim.Benchmark. Maybe I did something wrong, but I was not able to measure any significant performance difference between the two. In fact, I was not able to measure a significant difference between the fixed versions and the current version.

<details>
<summary>Code: Floating point number</summary>

```c#
namespace Pfim
{
    public class Dxt1Dds : CompressedDds
    {
        private const int PIXEL_DEPTH = 4;
        private const int DIV_SIZE = 4;

        public Dxt1Dds(DdsHeader header, PfimConfig config) : base(header, config)
        {
        }

        protected override byte PixelDepthBytes => PIXEL_DEPTH;
        protected override byte DivSize => DIV_SIZE;
        protected override byte CompressedBytesPerBlock => 8;
        public override ImageFormat Format => ImageFormat.Rgba32;
        public override int BitsPerPixel => 8 * PIXEL_DEPTH;

        private readonly Color8888[] colors = new Color8888[4];

        private struct Vec3
        {
            private float r;
            private float g;
            private float b;

            public static void FromRgb565(ushort rgb565, out Vec3 result)
            {
                const float F5 = 255f / 31f;
                const float F6 = 255f / 63f;
                result.r = ((rgb565 & 0x1f)) * F5;
                result.g = ((rgb565 & 0x7E0) >> 5) * F6;
                result.b = ((rgb565 & 0xF800) >> 11) * F5;
            }

            public static void Half(ref Vec3 a, ref Vec3 b, out Vec3 result)
            {
                result.r = (a.r + b.r) * 0.5f;
                result.g = (a.g + b.g) * 0.5f;
                result.b = (a.b + b.b) * 0.5f;
            }

            public static void Third(ref Vec3 large, ref Vec3 small, out Vec3 result)
            {
                const float THIRD = 1f / 3f;
                result.r = (2 * large.r + small.r) * THIRD;
                result.g = (2 * large.g + small.g) * THIRD;
                result.b = (2 * large.b + small.b) * THIRD;
            }

            public void As8bit(ref Color8888 result)
            {
                result.r = (byte)(r + 0.5f);
                result.g = (byte)(g + 0.5f);
                result.b = (byte)(b + 0.5f);
                result.a = 255;
            }
        }

        protected override int Decode(byte[] stream, byte[] data, int streamIndex, uint dataIndex, uint stride)
        {
            // Colors are stored in a pair of 16 bits
            ushort color0 = stream[streamIndex++];
            color0 |= (ushort)(stream[streamIndex++] << 8);

            ushort color1 = (stream[streamIndex++]);
            color1 |= (ushort)(stream[streamIndex++] << 8);

            // Extract R5G6B5
            Vec3.FromRgb565(color0, out var c0);
            Vec3.FromRgb565(color1, out var c1);

            c0.As8bit(ref colors[0]);
            c1.As8bit(ref colors[1]);

            // Used the two extracted colors to create two new colors that are
            // slightly different.
            if (color0 > color1)
            {
                Vec3.Third(ref c0, ref c1, out var c2);
                c2.As8bit(ref colors[2]);
                Vec3.Third(ref c1, ref c0, out var c3);
                c3.As8bit(ref colors[3]);
            }
            else
            {
                Vec3.Half(ref c0, ref c1, out var c2);
                c2.As8bit(ref colors[2]);

                colors[3].r = 0;
                colors[3].g = 0;
                colors[3].b = 0;
                colors[3].a = 0;
            }


            for (int i = 0; i < 4; i++)
            {
                // Every 2 bit is a code [0-3] and represent what color the
                // current pixel is

                // Read in a byte and thus 4 colors
                byte rowVal = stream[streamIndex++];
                for (int j = 0; j < 8; j += 2)
                {
                    // Extract code by shifting the row byte so that we can
                    // AND it with 3 and get a value [0-3]
                    var col = colors[(rowVal >> j) & 0x03];
                    data[dataIndex++] = col.r;
                    data[dataIndex++] = col.g;
                    data[dataIndex++] = col.b;
                    data[dataIndex++] = col.a;
                }

                // Jump down a row and start at the beginning of the row
                dataIndex += PIXEL_DEPTH * (stride - DIV_SIZE);
            }

            // Reset position to start of block
            return streamIndex;
        }
    }
}

```

</details>

<details>
<summary>Code: Fixed point ints</summary>

```c#
namespace Pfim
{
    public class Dxt1Dds : CompressedDds
    {
        private const int PIXEL_DEPTH = 4;
        private const int DIV_SIZE = 4;

        public Dxt1Dds(DdsHeader header, PfimConfig config) : base(header, config)
        {
        }

        protected override byte PixelDepthBytes => PIXEL_DEPTH;
        protected override byte DivSize => DIV_SIZE;
        protected override byte CompressedBytesPerBlock => 8;
        public override ImageFormat Format => ImageFormat.Rgba32;
        public override int BitsPerPixel => 8 * PIXEL_DEPTH;

        private readonly Color8888[] colors = new Color8888[4];

        struct FixedPointRGB
        {
            uint r;
            uint g;
            uint b;

            const uint MAX = 255 * 31 * 63 * 2 * 3;

            public static void FromRgb565(ushort rgb565, out FixedPointRGB result)
            {
                const uint F5 = MAX / 31;
                const uint F6 = MAX / 63;
                result.r = ((rgb565 & 0x1fu)) * F5;
                result.g = ((rgb565 & 0x7E0u) >> 5) * F6;
                result.b = ((rgb565 & 0xF800u) >> 11) * F5;
            }

            public static void Half(ref FixedPointRGB a, ref FixedPointRGB b, out FixedPointRGB result)
            {
                result.r = (a.r + b.r) / 2;
                result.g = (a.g + b.g) / 2;
                result.b = (a.b + b.b) / 2;
            }

            public static void Third(ref FixedPointRGB large, ref FixedPointRGB small, out FixedPointRGB result)
            {
                result.r = (2 * large.r + small.r) / 3;
                result.g = (2 * large.g + small.g) / 3;
                result.b = (2 * large.b + small.b) / 3;
            }

            public void As8bit(ref Color8888 result)
            {
                // This is the equivlent of 0.5.
                // Since int division always rounds down, we can add 0.5 to round to the nearest int.
                const uint OFFSET = MAX / 255 / 2;
                const uint D = MAX / 255;
                result.r = (byte)((r + OFFSET) / D);
                result.g = (byte)((g + OFFSET) / D);
                result.b = (byte)((b + OFFSET) / D);
                result.a = 255;
            }
        }

        protected override int Decode(byte[] stream, byte[] data, int streamIndex, uint dataIndex, uint stride)
        {
            // Colors are stored in a pair of 16 bits
            ushort color0 = stream[streamIndex++];
            color0 |= (ushort)(stream[streamIndex++] << 8);

            ushort color1 = (stream[streamIndex++]);
            color1 |= (ushort)(stream[streamIndex++] << 8);

            // Extract R5G6B5
            FixedPointRGB.FromRgb565(color0, out var c0);
            FixedPointRGB.FromRgb565(color1, out var c1);

            c0.As8bit(ref colors[0]);
            c1.As8bit(ref colors[1]);

            // Used the two extracted colors to create two new colors that are
            // slightly different.
            if (color0 > color1)
            {
                FixedPointRGB.Third(ref c0, ref c1, out var c2);
                c2.As8bit(ref colors[2]);
                FixedPointRGB.Third(ref c1, ref c0, out var c3);
                c3.As8bit(ref colors[3]);
            }
            else
            {
                FixedPointRGB.Half(ref c0, ref c1, out var c2);
                c2.As8bit(ref colors[2]);

                colors[3].r = 0;
                colors[3].g = 0;
                colors[3].b = 0;
                colors[3].a = 0;
            }


            for (int i = 0; i < 4; i++)
            {
                // Every 2 bit is a code [0-3] and represent what color the
                // current pixel is

                // Read in a byte and thus 4 colors
                byte rowVal = stream[streamIndex++];
                for (int j = 0; j < 8; j += 2)
                {
                    // Extract code by shifting the row byte so that we can
                    // AND it with 3 and get a value [0-3]
                    var col = colors[(rowVal >> j) & 0x03];
                    data[dataIndex++] = col.r;
                    data[dataIndex++] = col.g;
                    data[dataIndex++] = col.b;
                    data[dataIndex++] = col.a;
                }

                // Jump down a row and start at the beginning of the row
                dataIndex += PIXEL_DEPTH * (stride - DIV_SIZE);
            }

            // Reset position to start of block
            return streamIndex;
        }
    }
}

```

</details>

Note: I do not know much about how C#'s runtime JIT-optimizes code, so I wrote what I think optimized C# code is. The code is pretty terrible is what I'm saying.

While both of these implementations are correct accoring to a little testing, I very much perfer the floating point one, because there is less magic going on.

----

Reference image:
[BC1_UNORM_SRGB-47.zip](https://github.com/nickbabcock/Pfim/files/9292739/BC1_UNORM_SRGB-47.zip)

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR fixes #88. I applied my floating point solution (with a nicer interface) to DXT1, DXT3, and DXT5.

You can really see the rounding errors in the tests. They were a lot more common than I expected. Interestingly, the largest difference is 3. I only expected them to be off by one, so this was quite surprising. I checked that all changed colors are decoded correctly by comparing them with the color values Paint.net (which uses DirectX to read and write DDS files) has.

As for the hashes, I simply copied the actual values. There's probably some cool command that updates the these inline snapshots, so it would be nice if that was in the README.

I haven't done benchmarks yet, but they will likely not show much given my previous experience. I'll do them shortly.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
And I can't run benchmarks. It errors at some point and doesn't output anything. Maybe this has something to do with your recent project changes @nickbabcock? This is the error:

<details>

```
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.DllNotFoundException: Die DLL "DevIL": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
   bei DevILSharp.IL.GenImage()
   bei DevILSharp.Image.Load(Byte[] arr, ImageType imageType)
   bei Pfim.Benchmarks.DdsBenchmark.DevILSharp()
   bei BenchmarkDotNet.Autogenerated.Runnable_3.WorkloadActionNoUnroll(Int64 invokeCount)
   bei BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   bei BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   bei BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   bei BenchmarkDotNet.Autogenerated.Runnable_3.Run(IHost host, String benchmarkName)
   --- Ende der internen Ausnahmestapel?berwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
// Benchmark Process 5788 has exited with code -1.

Unbehandelte Ausnahme: System.InvalidOperationException: Die Sequenz enthält kein übereinstimmendes Element.
   bei System.Linq.Enumerable.Last[TSource](IEnumerable`1 source, Func`2 predicate)
   bei BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   bei BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   bei BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   bei BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   bei BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   bei BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   bei Pfim.Benchmarks.Program.Main(String[] args) in C:\Users\micha\Git\Pfim\src\Pfim.Benchmarks\Program.cs:Zeile 10.
// * Artifacts cleanup *
```

</details>

**Comment by nickbabcock** [comment]
> And I can't run benchmarks. It errors at some point and doesn't output anything. Maybe this has something to do with your recent project changes @nickbabcock? This is the error:

Yeah I'm not sure when the benchmarks broke, as I tried running the benchmarks many commits ago and they were still broken. This should now not happen again, as I've added running the benchmarks to CI.

Can you rebase off master and see if the benchmarks are fixed?

Sorry for all the dust I kicked up with the project changes. I wanted to get them in to make it easier for us to feel confident about any performance results

**Comment by RunDevelopment** [comment]
Very nice, they work now. Thank you! I'll post the results shortly.

**Comment by RunDevelopment** [comment]
Alright, the results are in and it's looking pretty good. As my initial run in #88 suggested, there is no noteable difference in performance, which is good.

DXT5 *seems* to have gotten faster, but that's probably just background process running and making the Before benchmark slower. The other benchmarked decoders also got faster in the After benchmark, so it's unlikely that my code changes increased performance.

Benchmarks: 

```ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1865 (21H2)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.400
  [Host]     : .NET 6.0.8 (6.0.822.36306), X64 RyuJIT
  DefaultJob : .NET 6.0.8 (6.0.822.36306), X64 RyuJIT
```

<details>
<summary>Before</summary>

|      Method |   Payload |         Mean |      Error |     StdDev |    StdErr |       Median |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|------------ |---------- |-------------:|-----------:|-----------:|----------:|-------------:|--------:|--------:|--------:|----------:|
|        **Pfim** | **32bit.dds** |     **2.372 μs** |  **0.0177 μs** |  **0.0157 μs** | **0.0042 μs** |     **2.374 μs** |  **0.0763** |       **-** |       **-** |     **496 B** |
|   FreeImage | 32bit.dds |   269.457 μs |  2.6861 μs |  2.3812 μs | 0.6364 μs |   269.907 μs | 12.2070 | 12.2070 | 12.2070 |   5,025 B |
| ImageMagick | 32bit.dds | 1,305.426 μs |  4.8699 μs |  4.5553 μs | 1.1762 μs | 1,305.282 μs |  1.9531 |       - |       - |  13,266 B |
|  DevILSharp | 32bit.dds |   115.278 μs |  0.3941 μs |  0.3686 μs | 0.0952 μs |   115.181 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt1.dds** |     **1.211 μs** |  **0.0197 μs** |  **0.0184 μs** | **0.0047 μs** |     **1.207 μs** |  **0.0839** |       **-** |       **-** |     **528 B** |
|   FreeImage |  dxt1.dds |    40.740 μs |  0.7989 μs |  1.3348 μs | 0.2225 μs |    40.457 μs | 13.4277 | 13.4277 | 13.4277 |   2,145 B |
| ImageMagick |  dxt1.dds |   410.323 μs |  3.1319 μs |  2.6153 μs | 0.7253 μs |   409.281 μs |  1.9531 |       - |       - |  13,246 B |
|  DevILSharp |  dxt1.dds |    48.750 μs |  0.2152 μs |  0.1908 μs | 0.0510 μs |    48.778 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt3.dds** |     **1.210 μs** |  **0.0129 μs** |  **0.0115 μs** | **0.0031 μs** |     **1.207 μs** |  **0.0839** |       **-** |       **-** |     **528 B** |
|   FreeImage |  dxt3.dds |    53.761 μs |  1.0052 μs |  0.9873 μs | 0.2468 μs |    53.868 μs | 13.4277 | 13.4277 | 13.4277 |   2,385 B |
| ImageMagick |  dxt3.dds |   457.618 μs |  3.7906 μs |  3.5457 μs | 0.9155 μs |   459.159 μs |  1.9531 |       - |       - |  13,246 B |
|  DevILSharp |  dxt3.dds |    76.815 μs |  1.1313 μs |  1.0582 μs | 0.2732 μs |    76.643 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt5.dds** |     **1.336 μs** |  **0.0266 μs** |  **0.0327 μs** | **0.0070 μs** |     **1.336 μs** |  **0.0896** |       **-** |       **-** |     **568 B** |
|   FreeImage |  dxt5.dds |    73.210 μs |  0.8810 μs |  0.7809 μs | 0.2087 μs |    73.232 μs | 13.5498 | 13.5498 | 13.5498 |   2,385 B |
| ImageMagick |  dxt5.dds |   525.018 μs | 10.2807 μs | 12.6256 μs | 2.6918 μs |   523.311 μs |  1.9531 |       - |       - |  13,253 B |
|  DevILSharp |  dxt5.dds |    74.928 μs |  1.2130 μs |  1.1347 μs | 0.2930 μs |    74.833 μs |       - |       - |       - |     128 B |

</details>

<details>
<summary>After</summary>

|      Method |   Payload |         Mean |      Error |     StdDev |    StdErr |       Median |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|------------ |---------- |-------------:|-----------:|-----------:|----------:|-------------:|--------:|--------:|--------:|----------:|
|        **Pfim** | **32bit.dds** |     **2.200 μs** |  **0.0277 μs** |  **0.0246 μs** | **0.0066 μs** |     **2.210 μs** |  **0.0763** |       **-** |       **-** |     **496 B** |
|   FreeImage | 32bit.dds |   270.120 μs |  2.3818 μs |  2.2279 μs | 0.5753 μs |   269.893 μs | 12.6953 | 12.6953 | 12.6953 |   5,025 B |
| ImageMagick | 32bit.dds | 1,273.669 μs | 14.9527 μs | 13.9868 μs | 3.6114 μs | 1,278.949 μs |  1.9531 |       - |       - |  13,266 B |
|  DevILSharp | 32bit.dds |   113.118 μs |  0.2183 μs |  0.1704 μs | 0.0492 μs |   113.107 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt1.dds** |     **1.222 μs** |  **0.0077 μs** |  **0.0072 μs** | **0.0019 μs** |     **1.219 μs** |  **0.0839** |       **-** |       **-** |     **528 B** |
|   FreeImage |  dxt1.dds |    40.208 μs |  0.4495 μs |  0.3753 μs | 0.1041 μs |    40.289 μs | 13.5498 | 13.5498 | 13.5498 |   2,145 B |
| ImageMagick |  dxt1.dds |   405.563 μs |  4.4299 μs |  4.1437 μs | 1.0699 μs |   404.365 μs |  1.9531 |       - |       - |  13,246 B |
|  DevILSharp |  dxt1.dds |    48.613 μs |  0.1528 μs |  0.1276 μs | 0.0354 μs |    48.636 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt3.dds** |     **1.201 μs** |  **0.0107 μs** |  **0.0100 μs** | **0.0026 μs** |     **1.205 μs** |  **0.0839** |       **-** |       **-** |     **528 B** |
|   FreeImage |  dxt3.dds |    50.879 μs |  0.8502 μs |  0.7537 μs | 0.2014 μs |    50.908 μs | 13.4277 | 13.4277 | 13.4277 |   2,385 B |
| ImageMagick |  dxt3.dds |   459.834 μs |  5.0993 μs |  4.7699 μs | 1.2316 μs |   461.547 μs |  1.9531 |       - |       - |  13,246 B |
|  DevILSharp |  dxt3.dds |    76.112 μs |  0.9255 μs |  0.8657 μs | 0.2235 μs |    76.339 μs |       - |       - |       - |     128 B |
|        **Pfim** |  **dxt5.dds** |     **1.224 μs** |  **0.0102 μs** |  **0.0095 μs** | **0.0025 μs** |     **1.220 μs** |  **0.0896** |       **-** |       **-** |     **568 B** |
|   FreeImage |  dxt5.dds |    68.391 μs |  1.1327 μs |  1.0595 μs | 0.2736 μs |    68.630 μs | 13.5498 | 13.5498 | 13.5498 |   2,385 B |
| ImageMagick |  dxt5.dds |   500.117 μs |  4.1895 μs |  3.2709 μs | 0.9442 μs |   500.309 μs |  1.9531 |       - |       - |  13,253 B |
|  DevILSharp |  dxt5.dds |    75.014 μs |  1.0198 μs |  0.9040 μs | 0.2416 μs |    75.160 μs |       - |       - |       - |     128 B |


</details>

**Comment by nickbabcock** [comment]
In case you want to run more dds benchmarks in the future you can target them better with:

```
dotnet run -c Release --project .\src\Pfim.Benchmarks -- --filter "*.DdsBenchmark.Pfim"
```

I ran the benchmarks too and didn't notice any deviations with this change.

---

> You can really see the rounding errors in the tests. They were a lot more common than I expected. Interestingly, the largest difference is 3. I only expected them to be off by one, so this was quite surprising

Wow yeah, it's a bummer this large of a correctness issue has gone unnoticed for so long. I'm unsure what the upper bound of the error is, but anything above zero is unacceptable 😄 

I ran the PR through some conversion tests and everything looked good:

```
dotnet run -c Release --project .\src\Pfim.Skia -- .\tests\Pfim.Tests\data\bc2-simple-srgb.dds
```

And spot checked the output the generated png with the dds image open in Paint.NET.

I did try and find a way to compare pfim output with a reference implementation, but I haven't solved the problem yet. I was hoping that [imagemagick's compare](https://stackoverflow.com/q/7940935/433785) would work, but it only supports BC1 images (afaik) and even for the BC1 image I tested on, it didn't work.

---

This PR looks good. I'll mull it over a little longer before merging and then releasing a new version.

**Pull request merged**
