### PR TITLE
Add support for BC7 decoding based on DirectXTex C++ library

### PR DESCRIPTION
**Pull request by ptasev**
I have taken code from the DirectXTex C++ library and made as minimal changes as possible to integrate decoding of BC7 data into Pfim and C#.

The output Bgra32 data can be sRGB or not depending on the input BC7 type. No conversions are made to have consistent type of output data no matter what.

The changes don't come with any benchmarks or tests, and I don't plan on adding any.

Feel free to make any changes as necessary if you'd like to make a merge.

### CODE REVIEW

**Comment by ptasev** [comment]
This is unrelated but in the DdsHeaderDxt10.cs NewDecoder method, there is a bug.

BC3 should use the Dxt5 decoder, and BC5 should use the BC5 decoder.

Docs: https://docs.microsoft.com/en-us/windows/win32/direct3d11/texture-block-compression-in-direct3d-11#bc1-bc2-and-b3-formats

**Comment by nickbabcock** [comment]
Thanks for adding support! Couple comments

> The changes don't come with any [...] tests, and I don't plan on adding any

At the minimum, I require something along the lines of an [image test](https://github.com/nickbabcock/Pfim/blob/master/tests/Pfim.Tests/ImageTests.cs) where the contents are hashed to ensure future refactoring doesn't accidentally break something.

I'd also like to see a usage example, so that your or I can add the capability of displaying BC7 images in something like the [Pfim.View.Forms sample](https://github.com/nickbabcock/Pfim/blob/master/src/Pfim.Viewer.Forms/Form1.cs)

> BC3 should use the Dxt5 decoder, and BC5 should use the BC5 decoder.

Yes, that does sound like a bug. Feel free to open another PR to fix this issue.

**Comment by ptasev** [comment]
I have added tests now.

The sample projects should work as is since they already support the ImageFormat of the Bc7 decoder output.

**Comment by nickbabcock** [comment]
Thank you very much, I appreciate the PR!

**Pull request merged**
