### PR TITLE
Fixed BC3 and BC5 using the wrong decoders

### PR DESCRIPTION
**Pull request by ptasev**
There was a bug where BC3 and BC5 based files were picking the wrong decoders.

Added BC5U as a pixel format as some image editors output that instead of DX10 based BC5 format. 

Added case statements for BC2 to use the DXT3 decoder.

There are now tests for BC2, BC3, BC5.

### CODE REVIEW

**Comment by ptasev** [comment]
I believe the error has to do with image3 in the TestImageProperties function.  For some reason reading from stream with the specified allocator is causing a different hash output.

**Comment by nickbabcock** [comment]
> I believe the error has to do with image3 in the TestImageProperties function. For some reason reading from stream with the specified allocator is causing a different hash output.

It's due to the same pixel buffer being used between multiple tests. One image may fill the entire pixel buffer, while another image may have padding in the stride. Pfim decoders don't overwrite this padding so there may be left over data from previous decodes that get factor into the content hash and cause the test failure.

There's two potential solution:

- Make the test content hash more precise
- Fill any extra padding with zeros.

Do you happen to have a preference?

**Comment by ptasev** [comment]
I'm not sure I completely understand but wouldn't the length passed into Hash64(image.Data, image.DataLen) take care of any extra padding? I assume then it would only hash the real data from the decode which is DataLen long?

**Comment by nickbabcock** [comment]
It ended up being something else. I've pushed a fix to master. Can you rebase and fix the merge conflicts?

**Comment by nickbabcock** [comment]
@ptasev your fixes and features have been included in the newly released 0.9.0 version.

**Pull request merged**
